version: "3.8"

services:
    database_backendbistro:
        image: postgres:latest
        container_name: database_backendbistro
        ports: 
            - 5432:5432
        restart: always
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=teste_bistro_clap
            
        volumes: 
            - pgdata:/data/postgres
        
    app:
        build: .
        container_name: backendbistro
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        links:
            - database_backendbistro
        depends_on: 
            - database_backendbistro   
volumes: 
    pgdata:
        driver: local
