version: "3.7"

services:
    database_backendbistro:
        image: postgres
        container_name: database_backendbistro
        ports: 
            - 5432:5432
        restart: always
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=teste_bistro_clap
        volumes: 
            - pgdata:/data/postgres
        networks:
            - backend
    app:
        build: .
        container_name: backendbistro
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        networks:
            - backend    

networks: 
    backend:
        driver: bridge
volumes: 
    pgdata:
        driver: local
